name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.3
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  http: ^0.13.0
  lints: ^2.0.0
  shelf_router_generator: ^1.0.4
  test: ^1.15.0
  test_process: ^2.0.3
